# vim: set ft=yaml:
# vim: set ts=2 sw=2 et:

all:
  children:
    # Group containing cloud-hosted servers (VPS)
    cloud:
      hosts:
        cloud-vps-001:
          ansible_host: cloud-vps-001.example.com
          host_tags:
          - vps
          - remote
          
    # Group containing Docker hosts
    docker:
      hosts:
        docker-node-001:
          ansible_host: docker-node-001.local
          host_tags:
          - docker
          - vm
        docker-node-002:
          ansible_host: docker-node-002.local
          host_tags:
          - docker
          - vm
          
    # Group containing Raspberry Pi nodes
    raspberrypi:
      hosts:
        rpi-node-100:
          ansible_host: rpi-node-100.local
          host_tags:
          - rpi4
        rpi-node-101:
          ansible_host: rpi-node-101.local
          host_tags:
          - rpi4
        rpi-node-500:
          ansible_host: rpi-node-500.local
          host_tags:
          - rpi5
          
    # Group containing on-premise servers
    servers:
      hosts:
        server-001:
          ansible_host: server-001.local
          host_tags:
          - proxmox
        server-002:
          ansible_host: server-002.local
          host_tags:
          - proxmox
        media-server:
          ansible_host: media-server.local
          host_tags:
          - media-server
        proxy-server:
          ansible_host: proxy-server.local
          host_tags:
          - nginx-proxy-manager
          - wireguard-server
        k3s-node-001:
          ansible_host: k3s-node-001.local
          host_tags:
          - vm
        k3s-node-002:
          ansible_host: k3s-node-002.local
          host_tags:
          - vm
          
    # Group containing laptops
    laptop:
      hosts:
        dev-laptop:
          ansible_host: laptop-wlan.local
          
    # Group containing workstations
    workstation:
      hosts:
        dev-workstation:
          ansible_host: dev-workstation.local

# Example of a custom grouping based on role or location
homelab:
  children:
    raspberrypi:
    servers: