---
# Example inventory file showing how to organize hosts and groups

all:
  children:
    # Group containing cloud-hosted servers
    cloud:
      hosts:
        webserver01:
          ansible_host: webserver01.example.com
        dbserver01:
          ansible_host: dbserver01.example.com
          
    # Group containing on-premise physical servers
    onprem:
      hosts:
        appserver01:
          ansible_host: appserver01.local
        appserver02:
          ansible_host: appserver02.local
        appserver03:
          ansible_host: appserver03.local