---
- name: Install fail2ban package
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Ensure fail2ban service is started and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Create fail2ban local configuration directory
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d
    state: directory
    mode: '0755'

- name: Configure fail2ban SSH jail
  ansible.builtin.template:
    src: sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    mode: '0644'
  notify: restart fail2ban

- name: Configure fail2ban defaults
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban